In [1]:
import pyodbc
import pandas as pd

In [ ]:
# To check what Microsoft Access Drivers exist
[x for x in pyodbc.drivers() if x.startswith('Microsoft Access Driver')]

# Graduation Rate Database

Given our research questions, the columns we need are:
- School year
- LEA_BEDS (12 digit code to specify category/subcategory of data sample)
- GRAD_PCT (denotes percentage of students who graduated in that LEA_BED)

In [2]:
DB_FILE = r'..\data\raw\gradrate\2025 High School Graduation Rate Researcher File.mdb' 
CONN_STR = (
    r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
    rf"DBQ={DB_FILE};"
)

In [3]:
conn = pyodbc.connect(CONN_STR)

In [4]:
df = pd.read_sql('SELECT * FROM GRAD_RATE_AND_OUTCOMES_2025', conn)
df

C:\Users\aamir\AppData\Local\Temp\ipykernel_60124\3974932901.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql('SELECT * FROM GRAD_RATE_AND_OUTCOMES_2025', conn)

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,INSTITUTION_ID,AGGREGATION_CODE,AGGREGATION_NAME,lea_beds,lea_name,NRC_CODE,NRC_DESC,...,LOCAL_CNT,LOCAL_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT
0,2024-25,0,Statewide,NaN,111111111111,All Districts and Charters,NaN,NaN,NaN,NaN,...,1993,1%,1490,1%,4951,2%,1253,1%,13785,7%
1,2024-25,0,Statewide,NaN,111111111111,All Districts and Charters,NaN,NaN,NaN,NaN,...,2,0%,3,1%,4,1%,1,0%,18,4%
2,2024-25,0,Statewide,NaN,111111111111,All Districts and Charters,NaN,NaN,NaN,NaN,...,1991,1%,1487,1%,4947,2%,1252,1%,13767,7%
3,2024-25,0,Statewide,NaN,111111111111,All Districts and Charters,NaN,NaN,NaN,NaN,...,541,1%,413,0%,2230,2%,315,0%,3332,4%
4,2024-25,0,Statewide,NaN,111111111111,All Districts and Charters,NaN,NaN,NaN,NaN,...,1452,1%,1077,1%,2721,3%,938,1%,10453,10%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224729,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,-,-,-,-,-,-,-,-,-,-
224730,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,3,33%,1,11%,0,0%,0,0%,4,44%
224731,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,1,8%,1,8%,1,8%,0,0%,5,38%
224732,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,2,40%,0,0%,1,20%,0,0%,2,40%
224733,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,2,9%,2,9%,4,18%,0,0%,7,32%

In [5]:
og = df

In [6]:
df.columns

Index(['REPORT_SCHOOL_YEAR', 'AGGREGATION_INDEX', 'AGGREGATION_TYPE',
       'INSTITUTION_ID', 'AGGREGATION_CODE', 'AGGREGATION_NAME', 'lea_beds',
       'lea_name', 'NRC_CODE', 'NRC_DESC', 'COUNTY_CODE', 'COUNTY_NAME',
       'NYC_IND', 'BOCES_CODE', 'BOCES_NAME', 'MEMBERSHIP_CODE',
       'MEMBERSHIP_DESC', 'subgroup_code', 'SUBGROUP_NAME', 'ENROLL_CNT',
       'GRAD_CNT', 'GRAD_PCT', 'REG_ADV_CNT', 'REG_ADV_PCT', 'REG_CNT',
       'REG_PCT', 'LOCAL_CNT', 'LOCAL_PCT', 'NON_DIPLOMA_CREDENTIAL_CNT',
       'NON_DIPLOMA_CREDENTIAL_PCT', 'STILL_ENR_CNT', 'STILL_ENR_PCT',
       'GED_CNT', 'GED_PCT', 'DROPOUT_CNT', 'DROPOUT_PCT'],
      dtype='str')

In [7]:
df = df.dropna(ignore_index=True)
df

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,INSTITUTION_ID,AGGREGATION_CODE,AGGREGATION_NAME,lea_beds,lea_name,NRC_CODE,NRC_DESC,...,LOCAL_CNT,LOCAL_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT
0,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
1,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
2,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,1,3%
3,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,4,6%
4,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142045,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,-,-,-,-,-,-,-,-,-,-
142046,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,3,33%,1,11%,0,0%,0,0%,4,44%
142047,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,1,8%,1,8%,1,8%,0,0%,5,38%
142048,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,2,40%,0,0%,1,20%,0,0%,2,40%
142049,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,2,9%,2,9%,4,18%,0,0%,7,32%

In [16]:
og.dropna(ignore_index=True).drop_duplicates(ignore_index=True)

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,INSTITUTION_ID,AGGREGATION_CODE,AGGREGATION_NAME,lea_beds,lea_name,NRC_CODE,NRC_DESC,...,LOCAL_CNT,LOCAL_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT
0,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
1,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
2,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,1,3%
3,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,4,6%
4,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142045,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,-,-,-,-,-,-,-,-,-,-
142046,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,3,33%,1,11%,0,0%,0,0%,4,44%
142047,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,1,8%,1,8%,1,8%,0,0%,5,38%
142048,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,2,40%,0,0%,1,20%,0,0%,2,40%
142049,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,2,9%,2,9%,4,18%,0,0%,7,32%

142050

In [28]:
df.loc[0]

REPORT_SCHOOL_YEAR                                                      2024-25
AGGREGATION_INDEX                                                             4
AGGREGATION_TYPE                                                         School
INSTITUTION_ID                                                     800000033912
AGGREGATION_CODE                                                   241001060003
AGGREGATION_NAME                                          DANSVILLE HIGH SCHOOL
lea_beds                                                           241001060000
lea_name                                                          DANSVILLE CSD
NRC_CODE                                                                      4
NRC_DESC                                                       RURAL HIGH NEEDS
COUNTY_CODE                                                                  24
COUNTY_NAME                                                          LIVINGSTON
NYC_IND                                                                       0
BOCES_CODE                                                                 2490
BOCES_NAME                    LIVINGSTON-GENESEE-STEUBEN-WYOMING(GENESEE VAL...
MEMBERSHIP_CODE                                                             6.0
MEMBERSHIP_DESC                              2019 Total Cohort - 6 Year Outcome
subgroup_code                                                                01
SUBGROUP_NAME                                                      All Students
ENROLL_CNT                                                                 96.0
GRAD_CNT                                                                     91
GRAD_PCT                                                                    95%
REG_ADV_CNT                                                                  28
REG_ADV_PCT                                                                 29%
REG_CNT                                                                      63
REG_PCT                                                                     66%
LOCAL_CNT                                                                     0
LOCAL_PCT                                                                    0%
NON_DIPLOMA_CREDENTIAL_CNT                                                    0
NON_DIPLOMA_CREDENTIAL_PCT                                                   0%
STILL_ENR_CNT                                                                 0
STILL_ENR_PCT                                                                0%
GED_CNT                                                                       0
GED_PCT                                                                      0%
DROPOUT_CNT                                                                   5
DROPOUT_PCT                                                                  5%
Name: 0, dtype: object

- Issue is need to find out what are the primary keys of the dataset, given below is best estimate
- Whenever last 4 digits are not '0000' in lea_beds, it means that it is a charter school


- ENTITY_CD is same as AGGREGATION_CODE in the two datasets

In [ ]:
df.loc[df.lea_beds == '241001060000', ['AGGREGATION_NAME', ].drop_duplicates()

0    DANSVILLE HIGH SCHOOL
Name: AGGREGATION_NAME, dtype: str

In [25]:
df[['REPORT_SCHOOL_YEAR','AGGREGATION_NAME', 'lea_beds',
       'lea_name','MEMBERSHIP_CODE',
       'MEMBERSHIP_DESC', 'subgroup_code', 'SUBGROUP_NAME']].drop_duplicates()#.query("subgroup_code == '01' & lea_beds == '310300010000'")

,REPORT_SCHOOL_YEAR,AGGREGATION_NAME,lea_beds,lea_name,MEMBERSHIP_CODE,MEMBERSHIP_DESC,subgroup_code,SUBGROUP_NAME
0,2024-25,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,6.0,2019 Total Cohort - 6 Year Outcome,01,All Students
1,2024-25,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,6.0,2019 Total Cohort - 6 Year Outcome,25,Parent Not in Armed Forces
2,2024-25,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,6.0,2019 Total Cohort - 6 Year Outcome,16,Not Economically Disadvantaged
3,2024-25,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,6.0,2019 Total Cohort - 6 Year Outcome,15,Economically Disadvantaged
4,2024-25,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,6.0,2019 Total Cohort - 6 Year Outcome,12,Not English Language Learner
...,...,...,...,...,...,...,...,...
142045,2024-25,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,18.0,2019 Total Cohort - 6 Year Outcome - August 2025,08,White
142046,2024-25,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,18.0,2019 Total Cohort - 6 Year Outcome - August 2025,06,Hispanic
142047,2024-25,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,18.0,2019 Total Cohort - 6 Year Outcome - August 2025,05,Black
142048,2024-25,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,18.0,2019 Total Cohort - 6 Year Outcome - August 2025,11,Students with Disabilities
142049,2024-25,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,18.0,2019 Total Cohort - 6 Year Outcome - August 2025,10,General Education Students

In [41]:
og.loc[(og.AGGREGATION_INDEX == '3') & (og.AGGREGATION_NAME == 'JOHNSON CITY CSD')]

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,INSTITUTION_ID,AGGREGATION_CODE,AGGREGATION_NAME,lea_beds,lea_name,NRC_CODE,NRC_DESC,...,LOCAL_CNT,LOCAL_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT
78180,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,5,3%,2,1%,4,2%,3,2%,20,10%
78181,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,5,3%,2,1%,4,2%,3,2%,20,10%
78182,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,2,3%,1,1%,0,0%,1,1%,2,3%
78183,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,3,3%,1,1%,4,3%,2,2%,18,15%
78184,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,1,20%,0,0%,0,0%,0,0%,0,0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78295,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,1,5%
78296,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,1,3%,0,0%,1,3%,1,3%,5,13%
78297,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,2,2%,2,2%,2,2%,0,0%,9,8%
78298,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,4,14%,2,7%,1,4%,0,0%,9,32%
78299,2024-25,3,District,800000054903,031502060000,JOHNSON CITY CSD,NaN,NaN,3,URBAN/SUBURBAN/HIGH NEEDS,...,1,1%,0,0%,3,2%,3,2%,11,6%

In [ ]:
df[['REPORT_SCHOOL_YEAR', 'AGGREGATION_INDEX', 'AGGREGATION_TYPE',
       'INSTITUTION_ID', 'AGGREGATION_CODE', 'AGGREGATION_NAME', 'lea_beds',
       'lea_name', 'NRC_CODE', 'NRC_DESC', 'COUNTY_CODE', 'COUNTY_NAME',
       'NYC_IND', 'BOCES_CODE', 'BOCES_NAME', 'MEMBERSHIP_CODE',
       'MEMBERSHIP_DESC', 'subgroup_code', 'SUBGROUP_NAME', 'ENROLL_CNT',
       'GRAD_CNT', 'GRAD_PCT', 'REG_ADV_CNT', 'REG_ADV_PCT', 'REG_CNT',
       'REG_PCT', 'LOCAL_CNT', 'LOCAL_PCT', 'NON_DIPLOMA_CREDENTIAL_CNT',
       'NON_DIPLOMA_CREDENTIAL_PCT', 'STILL_ENR_CNT', 'STILL_ENR_PCT',
       'GED_CNT', 'GED_PCT', 'DROPOUT_CNT', 'DROPOUT_PCT']]

,REPORT_SCHOOL_YEAR,AGGREGATION_INDEX,AGGREGATION_TYPE,INSTITUTION_ID,AGGREGATION_CODE,AGGREGATION_NAME,lea_beds,lea_name,NRC_CODE,NRC_DESC,...,LOCAL_CNT,LOCAL_PCT,NON_DIPLOMA_CREDENTIAL_CNT,NON_DIPLOMA_CREDENTIAL_PCT,STILL_ENR_CNT,STILL_ENR_PCT,GED_CNT,GED_PCT,DROPOUT_CNT,DROPOUT_PCT
0,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
1,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
2,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,1,3%
3,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,4,6%
4,2024-25,4,School,800000033912,241001060003,DANSVILLE HIGH SCHOOL,241001060000,DANSVILLE CSD,4,RURAL HIGH NEEDS,...,0,0%,0,0%,0,0%,0,0%,5,5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142045,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,-,-,-,-,-,-,-,-,-,-
142046,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,3,33%,1,11%,0,0%,0,0%,4,44%
142047,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,1,8%,1,8%,1,8%,0,0%,5,38%
142048,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,2,40%,0,0%,1,20%,0,0%,2,40%
142049,2024-25,4,School,800000093403,261600010114,PADILLA HIGH SCHOOL,261600010000,ROCHESTER CITY SD,2,LARGE CITY,...,2,9%,2,9%,4,18%,0,0%,7,32%

In [ ]:
df = pd.read_sql('SELECT SUBGROUP_NAME, REPORT_SCHOOL_YEAR, lea_beds, GRAD_PCT FROM GRAD_RATE_AND_OUTCOMES_2025', conn)
df

In [ ]:
# Drop all null columns
df = df.dropna(ignore_index=True)

In [ ]:
df.to_csv("../data/processed/grad_pct_per_ENTITY.csv", index=False)

In [34]:
conn.close()

# Enrollment database

Columns we need:

- ENTITY_CD (12 digit code to specify category/subcategory of data sample)
- YEAR
- PER_ECDIS

In [35]:
DB_FILE = r'..\data\raw\ENROLLMENT_2025\ENROLL2025_20251217.mdb' 
CONN_STR = (
    r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
    rf"DBQ={DB_FILE};"
)

conn = pyodbc.connect(CONN_STR)

In [36]:
df = pd.read_sql('SELECT ENTITY_CD, ENTITY_NAME, YEAR, PER_ECDIS FROM "Demographic Factors"', conn)
df

C:\Users\aamir\AppData\Local\Temp\ipykernel_60124\1474766920.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql('SELECT ENTITY_CD, ENTITY_NAME, YEAR, PER_ECDIS FROM "Demographic Factors"', conn)

,ENTITY_CD,ENTITY_NAME,YEAR,PER_ECDIS
0,000000000001,NYC Public Schools,2023.0,75.0
1,000000000002,Large Cities,2023.0,84.0
2,000000000003,High Need/Resource Urban-Suburban Districts,2023.0,74.0
3,000000000004,High Need/Resource Rural Districts,2023.0,60.0
4,000000000005,Average Need Districts,2023.0,44.0
...,...,...,...,...
16601,680601060002,PENN YAN MIDDLE SCHOOL,2025.0,54.0
16602,680601060005,PENN YAN ELEMENTARY SCHOOL,2025.0,63.0
16603,680801040000,DUNDEE CSD,2025.0,61.0
16604,680801040001,DUNDEE JUNIOR-SENIOR HIGH SCHOOL,2025.0,57.0
16605,680801040002,DUNDEE ELEMENTARY SCHOOL,2025.0,65.0

In [40]:
df.loc[(df.ENTITY_CD.str[-4:] == '0000') & (df.ENTITY_CD.str[:2] != '00')]

          ENTITY_CD         ENTITY_NAME    YEAR  PER_ECDIS
88     010100010000      ALBANY CITY SD  2023.0       71.0
99     031301040000         DEPOSIT CSD  2023.0       61.0
102    031401060000   WHITNEY POINT CSD  2023.0       59.0
106    031501060000  UNION-ENDICOTT CSD  2023.0       60.0
114    031502060000    JOHNSON CITY CSD  2023.0       68.0
...             ...                 ...     ...        ...
16590  671002040000         WYOMING CSD  2025.0       35.0
16592  671201060000           PERRY CSD  2025.0       48.0
16595  671501040000          WARSAW CSD  2025.0       48.0
16599  680601060000        PENN YAN CSD  2025.0       55.0
16603  680801040000          DUNDEE CSD  2025.0       61.0

[2153 rows x 4 columns]

In [ ]:
df = df.dropna()
df.to_csv('../data/processed/PER_ECDIS_per_ENTITY.csv', index=False)

In [ ]:
conn.close()