In [1]:
import plotly.express as px
import pandas as pd

1. Is there a correlation between graduation rates and number of economically disadvantaged students in each district?

In [7]:
df = pd.read_csv(r"..\data\processed\GRAD_PCT_vs_PER_ECDIS.csv")
df

,AGGREGATION_CODE,AGGREGATION_NAME,ENROLL_CNT,GRAD_CNT,GRAD_PCT,PER_ECDIS
0,240101040000,AVON CSD,73,69,0.95,0.34
1,240901040000,MT MORRIS CSD,54,50,0.93,0.64
2,241001060000,DANSVILLE CSD,122,100,0.82,0.55
3,430901060000,GORHAM-MIDDLESEX CSD (MARCUS WHITMAN,93,81,0.87,0.46
4,241101040000,DALTON-NUNDA CSD (KESHEQUA),52,47,0.90,0.47
...,...,...,...,...,...,...
663,580912060000,EASTPORT-SOUTH MANOR CSD,285,257,0.90,0.28
664,10623060000,NORTH COLONIE CSD,503,468,0.93,0.31
665,212101040000,CENTRAL VALLEY CSD AT ILION-MOHAWK,166,133,0.80,0.49
666,271201040000,OPPENHEIM-EPHRATAH-ST. JOHNSVILLE CS,53,47,0.89,0.64
667,151801040000,BOQUET VALLEY CSD,29,24,0.83,0.40

In [9]:
# Remove outlier rows based on enrollment count
lower = df["ENROLL_CNT"].quantile(0.10)
upper = df["ENROLL_CNT"].quantile(0.90)

df = df[(df["ENROLL_CNT"] >= lower) & (df["ENROLL_CNT"] <= upper)]
df

,AGGREGATION_CODE,AGGREGATION_NAME,ENROLL_CNT,GRAD_CNT,GRAD_PCT,PER_ECDIS
0,240101040000,AVON CSD,73,69,0.95,0.34
1,240901040000,MT MORRIS CSD,54,50,0.93,0.64
2,241001060000,DANSVILLE CSD,122,100,0.82,0.55
3,430901060000,GORHAM-MIDDLESEX CSD (MARCUS WHITMAN,93,81,0.87,0.46
4,241101040000,DALTON-NUNDA CSD (KESHEQUA),52,47,0.90,0.47
...,...,...,...,...,...,...
662,571502060000,CANISTEO-GREENWOOD CSD,89,85,0.96,0.58
663,580912060000,EASTPORT-SOUTH MANOR CSD,285,257,0.90,0.28
664,10623060000,NORTH COLONIE CSD,503,468,0.93,0.31
665,212101040000,CENTRAL VALLEY CSD AT ILION-MOHAWK,166,133,0.80,0.49
666,271201040000,OPPENHEIM-EPHRATAH-ST. JOHNSVILLE CS,53,47,0.89,0.64

In [10]:
fig = px.scatter(
    df,
    x="GRAD_PCT",
    y="PER_ECDIS",
    color="ENROLL_CNT",
    color_continuous_scale="Viridis",
    hover_name="AGGREGATION_NAME",
    labels={
        "GRAD_PCT": "Graduation Percentage",
        "PER_ECDIS": "Percent Economically Disadvantaged",
        "ENROLL_CNT": "Enrollment Count",
        "AGGREGATION_NAME": "District"
    },
    title="Graduation Rate vs Percentage Economically Disadvantaged"
)

fig.update_layout(
    template="plotly_white"
)

fig.show()

In [11]:
fig.write_html("../results/grad_rate_VS_per_ecdis.html")